### ISSUE TITLE
Mismatch in costs for cyclic's 'Fix and Dismantle' quest

### ISSUE THREAD

**Issue by wrincewind** [CaiganMythFang/FOG_of_Magic#13]
the quest icon for the fix and dismantle quest (the one that gets you a powered anvil, 3 xp pylons, a magma anvil, or a disassembler) is a gold coin with '44' written on it, leading me to believe i'd need to submit 44 gold coins. However when I did so, it changed to '14% complete'. Mousing over the icon reveals that it instead costs 300 coins. What gives?

**Comment by CaiganMythFang** [comment]
That is extremely strange, I see that as well. 

Any value over 126 gets reset due to a bug/issue with HQM (which is why I have multiple 100+ coin turn ins), so I'm wondering how this one turned into 300 but showed 44 for some odd reason.

This will be fixed in the next update, it SHOULD be 400, so something very weird happened. My apologies about that!
